language: node_js
node_js:
  - "5"
cache:
  directories:
  - node_modules
  - bower_components
before_script:
  - "./scripts/dev-setup"
script:
  - "./scripts/lint-js"
  - "./scripts/test-js --single-run"

